#if defined _zp_classes_const_included
	#endinput
#endif
#define _zp_classes_const_included

#include "include/zp7/zp_core_const.inc"

#define ZP_ABILITY:		_:
#define ZP_CLASS:		_:
#define ZP_GROUP:		_:
#define ZP_TYPE:		_:

#include "include/zp7/classes/ability_t.inc"
#include "include/zp7/classes/class_t.inc"
#include "include/zp7/classes/group_t.inc"
#include "include/zp7/classes/type_t.inc"
#include "include/zp7/classes/hclass_t.inc"
#include "include/zp7/classes/zclass_t.inc"